# -*- coding: utf-8 -*-
"""GenAI_Workshop_Day1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZqTC2KLaFf-zg5TJBJBRBjMdIjnn1Qir

Project 1: LLM Bot using GROQ
"""

!pip install gradio groq

import os
import gradio as gr
from groq import Groq
from google.colab import userdata

#1. Setup the Groq Client
#Ensure you have added GROQ_API_KEY to your Colab Secrets
client = Groq(api_key=userdata.get('GROQ_API_KEY'))
client

def chat_with_groq(message, history):
    messages = [{"role": "system","content": "You are a helpful and concise AI assistant."}]

    for human, assistant in history:
        messages.append({"role": "user", "content": human})
        messages.append({"role": "assistant", "content": assistant})

    messages.append({"role": "user", "content": message})

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=messages,
        temperature=0.7,
        max_tokens=1024,
        stream=True
    )
    partial_message = ""
    for chunk in response:
        if chunk.choices[0].delta.content is not None:
            partial_message += chunk.choices[0].delta.content
            yield partial_message

# 3. Create the Gradio Interface
demo = gr.ChatInterface(
    fn=chat_with_groq,
    title="Pragyan AI Groq - Lightning Chat",
    description="Experience fast responses using Groq LPUs.",
    examples=["Explain quantum computing in one sentence.",
              "Write a Python script to scrape a website."],
    theme="soft"
)
if __name__ == "__main__":
    demo.launch(share=True, debug=True)

"""Project 2: Hugging Face"""

!pip install transformers accelerate torch

# Import the necessary libraries
from transformers import AutoTokenizer, AutoModelForCausalLM
from transformers import pipeline

MODEL_NAME = "mistralai/Mistral-7B-Instruct-v0.2"

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype="auto"
)
generator = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=200
)

prompt = "Write a short marketing pitch for an AI-powered learning platform."

output = generator(prompt)
print(output[0]["generated_text"])

import gradio as gr
# Create a function to generate text
def generate_text(prompt, max_new_tokens=200):
    # The generator object is already defined in a previous cell
    output = generator(prompt, max_new_tokens=max_new_tokens)
    return output[0]["generated_text"]
'''
Create the Gradio Interface
1. Function
2.inputs
3.outputs
4.title
5.description
'''
# Create the Gradio interface
iface = gr.Interface(
    fn=generate_text, # The function to generate text
    inputs=[
        gr.Textbox(lines=5, label="Enter your prompt:"),
        #Textbox is a widget that allows the user to enter text
        gr.Slider(minimum=50, maximum=1000, step=50, value=200, label="Max New Tokens")
        #Slider is a widget that allows the user to select a value
    ],
    outputs=gr.Textbox(label="Generated Text"),
    title="PragyanAI - Mistral-7B-Instruct-v0.2 Text Generator",
    description="Generate text using the Mistral-7B-Instruct-v0.2 model from Hugging Face."
)

# Launch the interface
iface.launch(debug=True)